from fpdf import FPDF
from datetime import datetime
import io
import textwrap

class SentinURL_Report(FPDF):
    def _sanitize(self, txt):
        return str(txt).encode('latin-1', 'ignore').decode('latin-1')
        
    def cell(self, w, h=0, txt="", *args, **kwargs):
        super().cell(w, h, self._sanitize(txt), *args, **kwargs)
        
    def multi_cell(self, w, h, txt, *args, **kwargs):
        # Dynamically calculate conservative width based on current page width (minus margins)
        # Standard A4 is ~210mm. 190mm is a safe content area.
        # Average char width for Helvetica at size 10 is ~2mm.
        try:
            effective_width = (self.w - self.l_margin - self.r_margin)
            chars_per_line = int(effective_width / 2.1) # Conservative estimate
            wrapped_txt = textwrap.fill(self._sanitize(txt), width=chars_per_line)
            super().multi_cell(w, h, wrapped_txt, *args, **kwargs)
        except Exception:
            # Absolute fallback to prevent dashboard crash
            try:
                # If dynamic fails, try a very short wrap
                super().multi_cell(w, h, textwrap.fill(self._sanitize(txt), width=40), *args, **kwargs)
            except Exception:
                pass

    def header(self):
        # Logo placeholder or text
        self.set_font("helvetica", "B", 20)
        self.set_text_color(46, 134, 193)
        self.cell(0, 10, "SentinURL Threat Intelligence", border=False, ln=True, align="C")
        self.ln(5)
        
    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by SentinURL v3.3.0", align="C")

def generate_pdf_report(url, status, score, reasons, neural_analysis, domain):
    pdf = SentinURL_Report()
    pdf.add_page()
    
    # 1. Summary Card
    pdf.set_font("helvetica", "B", 16)
    pdf.cell(0, 10, f"Analysis Report: {domain}", ln=True)
    pdf.set_font("helvetica", "", 10)
    pdf.cell(0, 10, f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
    pdf.ln(5)
    
    # 2. Verdict Section
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(190, 10, " SYSTEM VERDICT", ln=True, fill=True)
    
    status_color = (46, 204, 113) if status == "Safe" else (231, 76, 60)
    pdf.set_text_color(*status_color)
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, f"[{status.upper()}] - Risk Score: {score}%", ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)
    
    # 3. Detection Reasons
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 10, "Key Indicators:", ln=True)
    pdf.set_font("helvetica", "", 10)
    for r in reasons:
        pdf.multi_cell(0, 8, f"- {r}")
    pdf.ln(5)
    
    # 4. Neural Markers Table
    if neural_analysis:
        pdf.set_font("helvetica", "B", 12)
        pdf.cell(0, 10, "Neural Logic Markers:", ln=True)
        
        # Table Header
        pdf.set_font("helvetica", "B", 10)
        pdf.set_fill_color(52, 152, 219)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(50, 8, "Factor", border=1, fill=True)
        pdf.cell(30, 8, "Risk", border=1, fill=True)
        pdf.cell(110, 8, "Observation", border=1, fill=True)
        pdf.ln()
        
        # Table Content
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("helvetica", "", 9)
        for m in neural_analysis:
            pdf.cell(50, 8, m['factor'], border=1)
            pdf.cell(30, 8, m['risk'], border=1)
            pdf.cell(110, 8, m['value'], border=1)
            pdf.ln()
    
    pdf.ln(10)
    pdf.set_font("helvetica", "I", 10)
    pdf.multi_cell(0, 5, "Disclaimer: This report was generated using hybrid machine learning assets. While accuracy is verified at 99.88%, this is an advisory tool and not a replacement for enterprise security protocols.")

    return bytes(pdf.output())
